spring:
  application:
    name: weatherAPI

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: post
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

weather:
  api:
    openWeatherMapUrl: http://api.openweathermap.org/data/2.5/weather?q=
    weatherApiUrl: http://api.weatherapi.com/v1/current.json?key=
    key: 25e38454a0f2af6bc314bc8b76dc55b1
    provider: openweathermap

timer:
  interval: 600000
  cache-ttl: 3600000

logging:
  level:
    root: INFO
    ru.anyline.weatherapi: DEBUG

