spring:
  r2dbc:
    url: r2dbc:h2:mem:///weather_data
    username: sa
    password: password
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

weather:
  timer:
    interval: 10000  #  (1 минута)
  cache:
    cleanup: "*/120 * * * * ?"
  scheduler:
    city: "Moscow"

api:
  weatherapi:
    url: "http://api.weatherapi.com/v1/forecast.json"
    key: 3432555972b64698985191252241508
  openweathermap:
    url: "http://api.openweathermap.org/data/2.5/weather"
    key: 25e38454a0f2af6bc314bc8b76dc55b1
