spring:
  application:
    name: WeatherAPI
  datasource:
    url: jdbc:h2:mem:weather
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

weather:
  timer:
    interval: 60000
  cache:
    cleanup: "*/60 * * * * ?"
  scheduler:
    city: "Moscow"

api:
  weatherapi:
    url: "http://api.weatherapi.com/v1/forecast.json"
    key: 3432555972b64698985191252241508
  openweathermap:
    url: "http://api.openweathermap.org/data/2.5/weather"
    key: 25e38454a0f2af6bc314bc8b76dc55b1
