weather:
  api:
    provider: openweathermap
    key: 

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/weatherdb
    username: postgres
    password: post

redis:
  host: localhost
  port: 6379

timer:
  interval: 10m
  cache-ttl: 1h
