weather:
  api:
    provider: openweathermap
    key: 25e38454a0f2af6bc314bc8b76dc55b1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: post

redis:
  host: localhost
  port: 6379

timer:
  interval: 10m
  cache-ttl: 1h
